name: API Spec CI

on:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle and Validate OpenAPI
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Bundle OpenAPI Spec
        run: |
          mkdir -p bundle
          redocly bundle openapi.yaml --output bundle/openapi.yaml

      - name: Validate OpenAPI Spec
        run: redocly lint bundle/openapi.yaml

      - name: Generate Docs
        run: redocly build-docs bundle/openapi.yaml -o bundle/index.html

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-bundle
          path: bundle/
          retention-days: 1

      - name: Generate Timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_OUTPUT

  deploy-pages:
    name: Deploy Docs
    needs: bundle
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: api-bundle
          path: dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

  create-pr:
    name: Create API PR
    needs: [bundle, deploy-pages]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Download Bundle
        uses: actions/download-artifact@v4
        with:
          name: api-bundle
          path: ${{ github.workspace }}/artifacts

      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: oversizedev/OversizeAPI
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: ${{ github.workspace }}/OversizeAPI
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          cd ${{ github.workspace }}/OversizeAPI
          git config user.name "API Updater Bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Create Branch
        run: |
          cd ${{ github.workspace }}/OversizeAPI
          git checkout -b update/api-${{ needs.bundle.outputs.timestamp }}

      - name: Copy Files
        run: |
          mkdir -p ${{ github.workspace }}/OversizeAPI/Sources/App
          cp ${{ github.workspace }}/artifacts/openapi.yaml ${{ github.workspace }}/OversizeAPI/Sources/App/openapi.yaml
          echo "Copied files structure:"
          ls -la ${{ github.workspace }}/OversizeAPI/Sources/App/

      - name: Debug Target Repo
        run: |
          echo "Current workspace: $GITHUB_WORKSPACE"
          echo "OversizeAPI contents:"
          ls -la ${{ github.workspace }}/OversizeAPI/Sources/App/
          echo "Artifacts contents:"
          ls -la ${{ github.workspace }}/artifacts

      - name: Check Changes
        id: check-changes
        run: |
          cd ${{ github.workspace }}/OversizeAPI
          git add -N Sources/App/openapi.yaml
          git diff --exit-code --quiet Sources/App/openapi.yaml || echo "changes_detected=true" >> $GITHUB_OUTPUT
          echo "Changes detected: ${{ steps.check-changes.outputs.changes_detected }}"

      - name: Commit and Push
        if: steps.check-changes.outputs.changes_detected == 'true'
        run: |
          cd ${{ github.workspace }}/OversizeAPI
          git add Sources/App/openapi.yaml
          git commit -m "chore: Update API spec from ${{ github.repository }}"
          git push origin update/api-${{ needs.bundle.outputs.timestamp }}

      - name: Check Changes
        id: check-changes
        run: |
          cd ${{ github.workspace }}/OversizeAPI
          # Явная проверка существования файла в целевой ветке
          if ! git ls-tree --name-only -r origin/main | grep -q "Sources/App/openapi.yaml"; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            # Сравнение содержимого файлов
            if ! diff -q Sources/App/openapi.yaml ${{ github.workspace }}/artifacts/openapi.yaml; then
              echo "changes_detected=true" >> $GITHUB_OUTPUT
            fi
          fi
      
      - name: Create PR
        if: steps.check-changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: ${{ github.workspace }}/OversizeAPI
          title: "API Specification Update"
          body: |
            Automatic API update from [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})
            **Documentation**: [${{ needs.deploy-pages.outputs.page_url }}](${{ needs.deploy-pages.outputs.page_url }})
          labels: automated,api-update
          branch: update/api-${{ needs.bundle.outputs.timestamp }}
          base: main
          delete-branch: false # Отключаем автоматическое удаление ветки
          commit-message: "chore: Update OpenAPI specification"
      
