name: Bundle OpenAPI Spec

on:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle and Validate OpenAPI
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Bundle OpenAPI Spec
        run: |
          mkdir -p bundle
          redocly bundle openapi.yaml --output bundle/openapi.yaml

      - name: Validate OpenAPI Spec
        run: redocly lint bundle/openapi.yaml

      - name: Generate Documentation
        run: |
          redocly build-docs bundle/openapi.yaml -o bundle/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: bundle/
          retention-days: 1

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bundle/openapi.yaml bundle/index.html
          git commit -m "chore: update bundled OpenAPI specification [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: bundle
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: bundle
          path: bundle

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: bundle

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-pr:
    name: Create PR in OversizeAPI
    needs: bundle
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: bundle
          path: bundle

      - name: Setup SSH and Git
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-add ~/.ssh/github_actions
          git config --global core.sshCommand 'ssh -i ~/.ssh/github_actions -o IdentitiesOnly=yes'

      - name: Checkout OversizeAPI
        uses: actions/checkout@v4
        with:
          repository: oversizedev/OversizeAPI
          path: OversizeAPI
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create Branch and Update OpenAPI Spec
        run: |
          cp bundle/openapi.yaml OversizeAPI/Sources/App/openapi.yaml
          cd OversizeAPI
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          branch_name="update-openapi-spec-${{ needs.bundle.outputs.timestamp }}"
          git checkout -b $branch_name
          git add Sources/App/openapi.yaml
          git commit -m "chore: update OpenAPI specification"
          GIT_SSH_COMMAND='ssh -i ~/.ssh/github_actions -o IdentitiesOnly=yes' git push origin $branch_name
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ACTIONS_TOKEN }}
          script: |
            const result = await github.rest.pulls.create({
              owner: 'oversizedev',
              repo: 'OversizeAPI',
              title: 'chore: update OpenAPI specification',
              body: `Automated OpenAPI specification update

              - Updated by: ${{ github.actor }}
              - Updated on: ${new Date().toISOString().replace('T', ' ').split('.')[0]}
              - Source: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}
              - Documentation: ${process.env.PAGES_URL}
              
              This PR was automatically created by GitHub Actions.`,
              head: process.env.BRANCH_NAME,
              base: 'main'
            });
            
            await github.rest.issues.addLabels({
              owner: 'oversizedev',
              repo: 'OversizeAPI',
              issue_number: result.data.number,
              labels: ['automated-pr', 'documentation']
            });
