name: Bundle OpenAPI Spec

on:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

jobs:
  bundle:
    name: Bundle and Validate OpenAPI
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Bundle OpenAPI Spec
        run: |
          mkdir -p bundle
          redocly bundle openapi.yaml --output bundle/openapi.yaml

      - name: Validate OpenAPI Spec
        run: redocly lint bundle/openapi.yaml

      - name: Generate Documentation
        run: |
          redocly build-docs bundle/openapi.yaml -o bundle/index.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: bundle/
          retention-days: 1

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bundle/openapi.yaml bundle/index.html
          git commit -m "chore: update bundled OpenAPI specification [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: bundle
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: bundle
          path: bundle

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: bundle

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  create-pr:
    name: Create PR in OversizeAPI
    needs: bundle
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
  
    steps:
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: bundle
          path: bundle
  
      - name: Checkout OversizeAPI
        uses: actions/checkout@v4
        with:
          repository: oversizedev/OversizeAPI
          token: ${{ secrets.ACTIONS_TOKEN }}
          path: OversizeAPI
  
      - name: Create New Branch
        run: |
          cd OversizeAPI
          git checkout -b update-openapi-${{ needs.bundle.outputs.timestamp }}
  
      - name: Copy OpenAPI Spec
        run: |
          cp bundle/openapi.yaml OversizeAPI/Sources/App/openapi.yaml
          cd OversizeAPI
          git status
  
      - name: Commit Changes
        run: |
          cd OversizeAPI
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Sources/App/openapi.yaml
          git commit -m "chore: update OpenAPI specification from $GITHUB_REPOSITORY"
  
      - name: Push Changes
        run: |
          cd OversizeAPI
          git push origin HEAD:update-openapi-${{ needs.bundle.outputs.timestamp }} \
            -f \
            --set-upstream origin update-openapi-${{ needs.bundle.outputs.timestamp }}
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: oversizedev/OversizeAPI
          path: OversizeAPI
          branch: update-openapi-${{ needs.bundle.outputs.timestamp }}
          title: "chore: update OpenAPI specification"
          body: |
            Automated update from ${{ github.repository }} (${{ github.sha }})
            
            - Source: ${{ github.server_url }}/${{ github.repository }}
            - Documentation: ${{ needs.deploy-pages.outputs.page_url }}
          labels: automated-pr,documentation
          delete-branch: true
  
